
version: '3.0'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc4-alpine
    volumes:
      - ./redis:/data

